CRUD pour créer un message
el1638en/ms-message-webapp pull request #1
Opened 2019-09-29 11:38 UTC by el1638en

2019-10-01 14:02 UTC, JulienBourgain requested changes

2019-10-02 22:53 UTC, el1638en commented on src/app/has-role.directive.ts
> +  stop$ = new Subject();
c'est un code obsolète. c'est retiré. Merci

2019-10-02 22:54 UTC, el1638en commented on src/app/services/auth.service.ts
> +    if (token) {
ok. done. merci

2019-10-02 22:54 UTC, el1638en commented on src/app/services/auth.service.ts
> +        break;
ok. done. merci

2019-10-02 22:54 UTC, el1638en commented on src/app/services/snackbar.service.ts
> +@Injectable()
ok. done. merci

2019-10-02 22:55 UTC, el1638en commented on src/app/resources/login.resource.ts
> +    readonly API_URL: string = `${environment.apiUrl}/api/login`;
ok. done. merci

2019-10-02 22:56 UTC, el1638en commented on src/app/edit-message/edit-message.component.spec.ts
> +fdescribe('EditMessageComponent', () => {
retiré. merci

2019-10-04 22:34 UTC, el1638en commented on src/app/app.component.scss
> +.spacer {
done. Merci

2019-10-04 22:35 UTC, el1638en commented on src/app/app.module.ts
> +export function HttpLoaderFactory(httpClient: HttpClient) {
done. Merci

2019-10-04 22:35 UTC, el1638en commented on src/app/app.module.ts
> +export const MY_FORMAT: MatDateFormats = {
done. Merci

2019-10-04 23:03 UTC, el1638en commented on src/app/app.module.ts
> +  providers: [
https://stackoverflow.com/questions/50848357/what-is-the-purpose-of-providedin-with-the-injectable-decorator-when-generating

True. Merci

2019-10-04 23:12 UTC, el1638en commented on src/app/app.module.ts
> +    {
done. merci

2019-10-07 08:05 UTC, ELEGBA commented on src/app/edit-message/edit-message.component.ts
> +    this.message = this.router.getCurrentNavigation().extras.state.target;
discuté avec Julien : 
ce n'est pas le composant qui gere les données du router. Cette partie est déléguée au service qui récupère l'ID inclus dans le router. Il fait sa recherche et fait son traitement métier. Il retourne au composant les données à afficher. Le composant ne doit plus manipuler un router.

2019-10-07 08:24 UTC, ELEGBA commented on src/app/login/login.component.ts
> +    this.loginForm = this.formBuilder.group({
Il faut plutôt utiliser les formgroup et formcontrol

2019-10-07 08:25 UTC, ELEGBA commented on src/app/resources/register.resource.ts
> +@Injectable()
done. Merci

2019-10-07 22:05 UTC, el1638en commented on src/app/app.component.html
> +<mat-toolbar color="primary" *ngIf="isAuthenticated()">
done. component header

2019-10-07 22:13 UTC, el1638en commented on src/app/edit-message/edit-message.component.html
> +          formControlName="content" required=true>
j'ai vu sur internet qu'utiliser l'attribut required simple suffit. Si required est absent, le champ est considéré comme non obligatoire.
https://www.w3schools.com/tags/att_required.asp
je l'ai testé en utilisant required simplement et ça fonctionne bien. Merci

2019-10-07 22:15 UTC, el1638en commented on src/app/edit-message/edit-message.component.ts
> +    } else {
done. merci

2019-10-07 22:18 UTC, el1638en commented on src/app/material.module.ts
> +    providers: [MatDatepickerModule],
erreur. un copier/coller. merci

2019-10-07 22:20 UTC, el1638en commented on src/app/services/auth-guard.service.ts
> +    } else {
je prefere le laisser pour plus de clarté

2019-10-08 08:04 UTC, ELEGBA commented on src/app/edit-message/edit-message.component.html
> +          formControlName="content" required=true>
https://www.w3.org/wiki/Doctypes_and_markup_styles. 
FInalement, c'est mieux d'écrire required = "true" ou required = "false"

2019-10-09 23:04 UTC, el1638en commented on src/app/app.component.ts
> +    translateService.addLangs(['en', 'fr']);
corrigé. c'est géré dans un composant header.

2019-10-09 23:06 UTC, el1638en commented on src/app/login/login.component.ts
> +    this.loginForm = this.formBuilder.group({
corrigé. Merci

2019-10-09 23:08 UTC, el1638en commented on src/app/edit-message/edit-message.component.spec.ts
> +    }).overrideComponent(EditMessageComponent, {
oui. je ferais dans une prochaine évolution. Pour le moment je me concentre uniquement sur la logue des components.

2019-10-09 23:10 UTC, el1638en commented on src/app/register/register.component.ts
> +    this.submitted = true;
mutualisation ok. RAF TU

2019-10-10 19:46 UTC, el1638en commented on src/app/edit-message/edit-message.component.ts
> +            // TODO : en cas d'erreur de la requete http, il faut traiter l'erreur.
corrigé.

2019-10-18 20:48 UTC, el1638en commented on src/app/new-message/new-message.component.ts
> +export class NewMessageComponent extends RxjsComponent implements OnInit {
done. Merci

2019-10-24 18:50 UTC, el1638en commented on src/app/models/message.ts
> +    constructor(value = {}) {
Done (utilisation du Partial<Message>). Merci

2019-10-24 18:53 UTC, el1638en commented on src/app/models/message.ts
> +    constructor(value = {}) {
Corrigé. J'ai utilisé le Partial<Message> pour initialiser les attributs qui sont renseignés. Si un attribut n'est pas renseigné, il ne sera pas initialisé. Merci

2019-10-27 08:12 UTC, el1638en commented on src/app/edit-message/edit-message.component.ts
> +    if (this.editMessageForm.invalid) {
done. edit-message et create-message ont été mutualisés dans message.component.ts. le snackbar a été ajouté. Merci

2019-11-07 23:57 UTC, merged